# Generated by Django 5.1.3 on 2024-12-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enterprise', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_recruitment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CareerMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.IntegerField()),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_matching.career')),
            ],
        ),
        migrations.CreateModel(
            name='CareerUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.IntegerField()),
                ('number_of_recruitment', models.IntegerField()),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_matching.career')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_matching.enterprise')),
            ],
        ),
    ]
