# Generated by Django 5.1.3 on 2024-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0002_alter_career_id_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
