# Generated by Django 5.1.3 on 2024-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0003_enterprise_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
