# Generated by Django 5.1.3 on 2024-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0004_enterprise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_image/'),
        ),
        migrations.AddField(
            model_name='career',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
