# Generated by Django 5.1.3 on 2024-12-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0005_career_date_career_image_career_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career_image/'),
        ),
    ]
