# Generated by Django 5.1.3 on 2024-12-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0006_alter_career_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='id_enterprise',
            new_name='enterprise',
        ),
        migrations.AddField(
            model_name='career',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
