# Generated by Django 5.1.3 on 2024-12-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0007_rename_id_enterprise_career_enterprise_career_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
