# Generated by Django 5.1.3 on 2024-12-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0012_careeruniversity_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
