# Generated by Django 5.1.3 on 2024-12-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matching', '0014_enterprisestudent_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisestudent',
            name='status_student',
            field=models.CharField(blank=True, choices=[('Trượt', 'Trượt'), ('Đang thực tập', 'Đang thực tập'), ('Hoàn thành', 'Hoàn thành')], default='Đang thực tập', max_length=255, null=True),
        ),
    ]
