# Generated by Django 5.1.3 on 2024-12-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
