# Generated by Django 5.1.3 on 2024-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_student', '0003_major_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_admission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.CharField(max_length=10),
        ),
    ]
