# Generated by Django 5.1.3 on 2024-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_student', '0004_student_date_of_birth_student_year_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
