# Generated by Django 5.1.3 on 2024-12-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_student', '0006_student_awards_student_gpa_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='available',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quote',
        ),
        migrations.AlterField(
            model_name='student',
            name='Awards',
            field=models.TextField(blank=True, default=''),
        ),
    ]
