# Generated by Django 5.1.3 on 2024-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_student', '0007_remove_student_available_remove_student_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True),
        ),
    ]
