# Generated by Django 5.1.3 on 2024-12-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_matching', '0012_careeruniversity_is_deleted'),
        ('manage_student', '0005_alter_student_year_of_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=50)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_matching.career')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_student.student')),
            ],
        ),
    ]
